using Controller550W.Core;
using Xunit;
namespace Controller550W.Tests;
public class V2Tests
{
    readonly DateTimeOffset at=DateTimeOffset.Parse("2026-09-30T10:00:00Z");
    [Fact]public void OrdinaryExitNeverRequestsShutdownAnimation(){var state=new AppLifecycle();var p=new AppProfile{OptimizedShutdown=true};state.Update(p,new(1,1),at,true);var exit=state.Update(p,new(0,0),at.AddSeconds(1));Assert.True(exit.Stopped);Assert.Null(exit.Animation);}
    [Fact]public void ManagedLaunchDeduplicatesFirstProcessAndWindow(){var state=new AppLifecycle();var p=new AppProfile();state.Update(p,new(0,0),at,true);state.BeginManagedLaunch("managed",at);Assert.Null(state.Update(p,new(1,0),at.AddMilliseconds(300)).Animation);Assert.Null(state.Update(p,new(1,1),at.AddMilliseconds(700)).Animation);state.MarkManagedReady();Assert.False(state.ExpectedLaunch(at.AddSeconds(1)));}
    [Fact]public void StartupWindowRebuildDoesNotRepeatBoot(){var state=new AppLifecycle();var p=new AppProfile();state.Update(p,new(0,0),at);Assert.Equal(AnimationKind.Boot,state.Update(p,new(1,1),at.AddSeconds(1)).Animation);Assert.False(state.Update(p,new(1,0),at.AddMilliseconds(1300)).Stopped);Assert.Null(state.Update(p,new(1,1),at.AddMilliseconds(1500)).Animation);}
    [Fact]public void CloseRequiresConfirmationAndRenderedOverlay(){var state=new ManagedCloseLifecycle();Assert.True(state.TryRequest());Assert.False(state.TryRequest());state.Preparing();state.WaitConfirmation();Assert.False(state.RequestNormalClose(true));Assert.True(state.Confirm());Assert.False(state.RequestNormalClose(false));Assert.True(state.RequestNormalClose(true));Assert.False(state.RequestNormalClose(true));Assert.Equal(ManagedClosePhase.AppClosing,state.Phase);}
    [Fact]public void CancelReturnsToRunningWithoutClose(){var state=new ManagedCloseLifecycle();state.TryRequest();state.Preparing();state.WaitConfirmation();state.Cancel();Assert.Equal(ManagedClosePhase.Running,state.Phase);Assert.False(state.RequestNormalClose(true));Assert.True(state.TryRequest());}
    [Fact]public void ConfirmedFailureAllowsNormalCloseExactlyOnce(){var state=new ManagedCloseLifecycle();state.TryRequest();state.Preparing();state.WaitConfirmation();state.Confirm();Assert.True(state.RequestNormalClose(false,true));Assert.False(state.RequestNormalClose(false,true));state.Complete();Assert.True(state.TryRequest());}
    [Fact]public void DefaultsKeepLaunchAndCloseIndependent(){var p=new AppProfile{LaunchMode=LaunchMode.OptimizedShortcut};Assert.False(p.OptimizedShutdown);Assert.True(p.CloseConfirmation);Assert.Equal(CloseEntry.ManagedClose,p.CloseEntry);Assert.Equal(4000,p.MinimumBootTimeMs);Assert.Equal("movie_red",new ControllerSettings().Animation.ColorProfile);}
    [Fact]public void ProfileV2SettingsRoundTrip(){var p=new AppProfile{OptimizedShutdown=true,LaunchKind=LaunchTargetKind.AppUserModelId,LaunchTarget="Family!App",WindowPresentation=WindowPresentation.Center,CoreCachePath="core.png",AppLaunchOffsetMs=600};var copy=WireJson.Clone(p);Assert.True(copy.OptimizedShutdown);Assert.Equal(p.LaunchTarget,copy.LaunchTarget);Assert.Equal(WindowPresentation.Center,copy.WindowPresentation);Assert.Equal("core.png",copy.CoreCachePath);}
    [Fact]public void MigratesV1WithoutLosingAudioOrProfiles(){var dir=Path.Combine(Path.GetTempPath(),"550W-v2-"+Guid.NewGuid().ToString("N"));try{Directory.CreateDirectory(dir);File.WriteAllText(Path.Combine(dir,"settings.json"),"{\"schemaVersion\":1,\"animation\":{\"colorProfile\":\"amber\",\"minimumBootMs\":3500},\"audio\":{\"soundVolume\":39},\"profiles\":[{\"displayName\":\"User AI\",\"minimumBootTimeMs\":3500,\"executablePath\":\"app.exe\"}]}");var c=new ConfigStore(dir).Load();Assert.Equal(3,c.SchemaVersion);Assert.Equal("movie_red",c.Animation.ColorProfile);Assert.Equal(4000,c.Profiles[0].MinimumBootTimeMs);Assert.Equal(39,c.Audio.SoundVolume);Assert.False(c.Profiles[0].OptimizedShutdown);}finally{Directory.Delete(dir,true);}}
    [Theory][InlineData(1)][InlineData(1.25)][InlineData(1.5)][InlineData(2)]public void CaptionCoordinatesRemainPhysicalAcrossDpi(double scale){var w=new PhysicalRect(-1920,120,-1920+(int)(1600*scale),120+(int)(800*scale));var c=new PhysicalRect(w.Right-(int)(45*scale),w.Top,w.Right,w.Top+(int)(30*scale));Assert.True(CaptionGeometry.IsReliable(w,c));Assert.True(c.Contains(c.Left+1,c.Top+1));Assert.False(c.Contains(c.Right+1,c.Top));}
    [Fact]public void UnsafeCaptionRectangleFallsBack(){Assert.False(CaptionGeometry.IsReliable(new(0,0,1600,900),new(900,800,1000,850)));Assert.False(CaptionGeometry.IsReliable(new(0,0,1600,900),new(1300,0,1600,30)));}
}
