const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),images=path.join(root,'docs/images-v3');fs.mkdirSync(images,{recursive:true});
const results=[];let browser,server;
const baseSession=(kind='boot')=>({kind,displayName:'Fixture AI',demo:true,minimumBootTimeMs:4000,settings:{durationMultiplier:1,colorProfile:'movie_red',systemLabel:'550W',centerRevealMs:900,readyMs:600,shutdownMs:2600,fadeMs:300,bootWatchdogMs:24000,shutdownWatchdogMs:5000,waitForReady:true,allowEscape:true,allowClickSkip:false},audio:{soundEnabled:true,soundVolume:0,voiceEnabled:false,voiceVolume:0,muted:false,bootVoice:true,shutdownVoice:true,phrases:{READY:'{app} interface ready',SHUTDOWN:'正在终止人工智能会话。'}}});
async function run(name,test){try{const detail=await test();results.push({name,pass:true,...detail});console.log('PASS '+name);}catch(e){results.push({name,pass:false,error:e.stack});console.log('FAIL '+name+' '+e.message);}fs.writeFileSync(path.join(root,'docs/web-test-v3-results.json'),JSON.stringify(results,null,2));}
const state=p=>p.evaluate(()=>Controller550W.getState());
const send=(p,m)=>p.evaluate(value=>Controller550W.receive(value),m);
async function page(kind='boot',session=baseSession(kind),options={}){const p=await browser.newPage({viewport:{width:1920,height:1080},...options});p.errors=[];p.on('pageerror',e=>p.errors.push(e.message));await p.goto(url+'/Themes/550W/'+kind+'.html?controlled');await p.waitForFunction(()=>window.Controller550W);await send(p,{type:'init',session});return p;}
let url;
(async()=>{
 server=http.createServer((req,res)=>{let file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':file.endsWith('.json')?'application/json':file.endsWith('.png')?'image/png':file.endsWith('.wav')?'audio/wav':'application/octet-stream');fs.createReadStream(file).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));url='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({headless:true,executablePath:process.env.EDGE_PATH||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',args:['--autoplay-policy=no-user-gesture-required']});
 await run('V3 continuous core → particles → 550W → full-screen particles → original windows',async()=>{
   const s=baseSession();s.settings.readyMs=500;s.settings.handoffCompressMs=700;s.settings.fadeMs=600;
   const p=await page('boot',s);await p.evaluate(()=>{window.visualSamples=[];window.sampler=setInterval(()=>{const s=Controller550W.getState();if(s.intro)visualSamples.push({at:s.elapsed,...s.intro});},16);});
   await send(p,{type:'target',target:{processDetected:true,windowDetected:true,ready:true}});
   for(const [phase,pause,file]of [['CORE_HOLD',180,'01-core'],['CORE_PARTICLES',330,'02-core-particles'],['PARTICLE_RESIDUE',120,'03-particle-cloud'],['LOGO_ASSEMBLING',530,'04-logo-assembly'],['LOGO_HOLD',180,'05-550w-logo'],['LOGO_BURST',720,'06-fullscreen-particles'],['MULTIWINDOW_REVEAL',300,'07-windows-crossfade']]){
     await p.waitForFunction(value=>Controller550W.getState().intro?.phase===value,phase,{timeout:12000,polling:16});await p.waitForTimeout(pause);await p.screenshot({path:path.join(images,file+'.png')});
   }
   const spread=(await state(p)).intro.coverage;assert(spread.left<100&&spread.right>1800&&spread.top<100&&spread.bottom>950);
   await p.waitForFunction(()=>Controller550W.getState().handoffInProgress,{},{timeout:22000,polling:16});await p.waitForTimeout(180);
   const handoff=await p.evaluate(()=>{const sh=document.querySelector('.controller-host').shadowRoot,c=sh.querySelector('.composition-layer'),matrix=new DOMMatrix(getComputedStyle(c).transform);return{scaleX:matrix.a,scaleY:matrix.d,opacity:Number(getComputedStyle(c).opacity),body:getComputedStyle(document.body).backgroundColor,stage:getComputedStyle(sh.querySelector('.dsh550c-stage')).backgroundColor,children:c.querySelectorAll('.window,#app,#final').length};});
   assert(handoff.scaleX>0&&handoff.scaleX<1);assert.equal(handoff.scaleY,1);assert(handoff.opacity>0&&handoff.opacity<1);assert.equal(handoff.body,'rgba(0, 0, 0, 0)');assert.equal(handoff.stage,'rgba(0, 0, 0, 0)');assert(handoff.children>0);
   await p.screenshot({path:path.join(images,'08-content-handoff.png'),omitBackground:true});await p.waitForFunction(()=>Controller550W.getState().finished);
   const end=await state(p),samples=await p.evaluate(()=>{clearInterval(sampler);return visualSamples;});assert(!samples.some(x=>x.coreVisible&&x.logoVisible),'Core and logo must never overlap');assert(samples.some(x=>x.phase==='PARTICLE_RESIDUE'&&!x.coreVisible&&!x.logoVisible));
   const sequence=['CORE_HOLD','CORE_PARTICLES','PARTICLE_RESIDUE','LOGO_ASSEMBLING','LOGO_HOLD','LOGO_BURST','MULTIWINDOW_REVEAL','MULTIWINDOW_ACTIVE'];assert.deepEqual(end.events.filter(e=>sequence.includes(e.type)).map(e=>e.type),sequence);assert.equal(end.intro.count,700);assert.equal(end.intro.disposed,true);assert.equal(end.events.filter(e=>e.type==='HANDOFF_BEGIN').length,1);assert.equal(end.events.find(e=>e.type==='REQUEST_FADE').detail.handoffComplete,true);assert.equal(p.errors.length,0);await p.close();return{events:end.events,handoff,spread,overlapSamples:samples.length};
 });
 await run('V3 timing and particle controls alter the actual timeline',async()=>{
   const s=baseSession();Object.assign(s.settings,{coreHoldMs:420,coreDissolveMs:330,particleResidueMs:260,logoRevealMs:390,logoHoldMs:250,logoBurstMs:340,multiWindowRevealMs:300,particleCount:1100,particleSize:4,particleSpread:1.4});
   const p=await page('boot',s);await p.waitForFunction(()=>Controller550W.getState().intro?.phase==='MULTIWINDOW_ACTIVE',{},{timeout:8000});const a=await state(p),events=a.events,t=name=>events.find(e=>e.type===name).at;for(const [from,to,ms] of [['CORE_HOLD','CORE_PARTICLES',420],['CORE_PARTICLES','PARTICLE_RESIDUE',330],['PARTICLE_RESIDUE','LOGO_ASSEMBLING',260],['LOGO_ASSEMBLING','LOGO_HOLD',390],['LOGO_HOLD','LOGO_BURST',250],['LOGO_BURST','MULTIWINDOW_REVEAL',340],['MULTIWINDOW_REVEAL','MULTIWINDOW_ACTIVE',300]])assert(t(to)-t(from)>=ms-25,from+' duration');assert.equal(a.intro.count,1100);assert.equal(a.intro.config.particleSize,4);assert.equal(a.intro.config.particleSpread,1.4);await p.keyboard.press('Escape');assert((await state(p)).intro.disposed);await p.close();return{events};
 });
 await run('V3 cancellation disposes particles during every new intro phase',async()=>{
   const names=['CORE_HOLD','CORE_PARTICLES','PARTICLE_RESIDUE','LOGO_ASSEMBLING','LOGO_HOLD','LOGO_BURST','MULTIWINDOW_REVEAL'];for(const name of names){const s=baseSession();s.settings.durationMultiplier=.25;const p=await page('boot',s);await p.waitForFunction(value=>Controller550W.getState().intro?.phase===value,name,{timeout:6000,polling:5});await send(p,{type:'cancel'});await p.waitForTimeout(50);const a=await state(p);assert(a.finished);assert(a.intro.disposed);assert.equal(a.events.filter(e=>e.type==='REQUEST_FADE').length,1);assert.equal(p.errors.length,0);await p.close();}return{phases:names};
 });
 await run('Original nine phases / nine windows / 47 nodes / no early handoff',async()=>{
   const p=await page();await send(p,{type:'target',target:{processDetected:true,windowDetected:true,ready:true}});const at=Date.now();
   for(const ms of [200,500,1000,2000,3000,4000,6500,8200]){await p.waitForTimeout(Math.max(0,ms-(Date.now()-at)));if(ms===200)assert.equal(await p.evaluate(()=>getComputedStyle(document.querySelector('.controller-host').shadowRoot.querySelector('#boot')).visibility),'hidden');await p.screenshot({path:path.join(images,'boot-'+ms+'ms.png')});}
   assert.equal((await state(p)).finished,false);await p.waitForFunction(()=>Controller550W.getState().finished,{},{timeout:22000});const s=await state(p);
   assert.equal(s.nodes,47);assert.equal(s.modules.length,9);assert.deepEqual(s.modules.map(x=>x.name),['ACCESS AUTHORIZATION','LINK MONITOR','SIGNAL POLLUTION','AUTH BYPASS INJECTION','OVERRIDE CONTROLLER','ANOMALY · UAV-07','ANOMALY · UAV-23','OVERRIDE SUMMARY','EMERGENCY DISARM']);assert(s.events.find(x=>x.type==='TARGET_READY').at>=s.events.find(x=>x.type==='CHOREOGRAPHY_COMPLETE').at);assert(s.events.find(x=>x.type==='TARGET_READY').at>=4000);assert.equal(s.events.filter(x=>x.type==='LOGO_BEGIN').length,1);assert.equal(p.errors.length,0);await p.close();return{modules:s.modules,events:s.events,nodes:s.nodes};
 });
 await run('Waiting loop holds final mother state and plays no repeated sounds',async()=>{
   const p=await page();await send(p,{type:'target',target:{processDetected:true,windowDetected:true,ready:false}});await p.waitForFunction(()=>Controller550W.getState().phase==='WAITING',{},{timeout:21000});await p.screenshot({path:path.join(images,'waiting.png')});const a=await state(p);await p.waitForTimeout(1600);const b=await state(p);assert.equal(b.finished,false);assert.equal(b.modules.length,a.modules.length);assert.equal(b.audioEvents.length,a.audioEvents.length);await send(p,{type:'target',target:{processDetected:true,windowDetected:true,ready:true}});await p.waitForFunction(()=>Controller550W.getState().phase==='SYSTEM READY');await p.waitForTimeout(300);await p.screenshot({path:path.join(images,'ready.png')});await p.waitForFunction(()=>Controller550W.getState().finished);const s=await state(p);assert.equal(s.events.filter(x=>x.type==='WAITING_LOOP_READY').length,1);assert.equal(s.audioEvents.filter(x=>x.key==='PROCESS_DETECTED').length,1);assert.equal(s.audioEvents.filter(x=>x.key==='CHECK_OK').length,3);await p.close();return{waitMs:1600,events:s.events,audio:s.audioEvents};
 });
 await run('Shutdown silently preloads, then independently collapses on activation',async()=>{
   const s=baseSession('shutdown');s.preload=true;const p=await page('shutdown',s);await p.waitForFunction(()=>Controller550W.getState().events.some(x=>x.type==='PRELOAD_READY'));await p.waitForTimeout(400);let before=await state(p);assert.equal(before.audioEvents.length,0);assert(!before.events.some(x=>x.type==='SHUTDOWN_BEGIN'));
   await p.screenshot({path:path.join(images,'shutdown-preloaded.png')});
   await send(p,{type:'activate'});await p.waitForTimeout(300);await p.screenshot({path:path.join(images,'shutdown-modules.png')});await p.waitForTimeout(950);await p.screenshot({path:path.join(images,'shutdown-core.png')});await p.waitForTimeout(600);await p.screenshot({path:path.join(images,'shutdown-crt.png')});await p.waitForFunction(()=>Controller550W.getState().finished);const a=await state(p);assert.equal(a.events.filter(x=>x.type==='SHUTDOWN_BEGIN').length,1);assert.deepEqual(a.events.filter(x=>['SHUTDOWN_BEGIN','HUD_OFFLINE','CRT_COLLAPSE','POWER_OFF'].includes(x.type)).map(x=>x.type),['SHUTDOWN_BEGIN','HUD_OFFLINE','CRT_COLLAPSE','POWER_OFF']);assert(a.events.find(x=>x.type==='REQUEST_FADE').at<3300);assert.equal(a.audioEvents.filter(x=>x.key==='RELAY_OFF').length,3);await p.close();return{events:a.events};
 });
 await run('Cancel preload releases silently',async()=>{const s=baseSession('shutdown');s.preload=true;const p=await page('shutdown',s);await p.waitForFunction(()=>Controller550W.getState().events.some(x=>x.type==='PRELOAD_READY'));await send(p,{type:'cancel'});assert((await state(p)).finished);assert.equal((await state(p)).audioEvents.length,0);await p.close();});
 for(const color of ['movie_red','amber','green','cyan','white'])await run('Palette '+color,async()=>{const s=baseSession('shutdown');s.preload=true;s.settings.colorProfile=color;const p=await page('shutdown',s);await p.waitForFunction(()=>Controller550W.getState().events.some(x=>x.type==='PRELOAD_READY'));const c=await p.evaluate(()=>getComputedStyle(document.querySelector('.controller-host')).getPropertyValue('--amber').trim());assert.equal(c,{movie_red:'#e05030',amber:'#e8a020',green:'#82ba6b',cyan:'#57a9b1',white:'#b5b9bc'}[color]);await p.close();return{primary:c};});
 for(const dpi of [1,1.25,1.5,2])await run('Uniform canvas / browser DPI '+dpi,async()=>{const s=baseSession('shutdown');s.preload=true;const p=await page('shutdown',s,{viewport:{width:1366,height:768},deviceScaleFactor:dpi});await p.waitForFunction(()=>Controller550W.getState().events.some(x=>x.type==='PRELOAD_READY'));const a=await p.evaluate(()=>{const shadow=document.querySelector('.controller-host').shadowRoot;const r=shadow.querySelector('.dsh550c-stage').getBoundingClientRect();return{width:r.width,height:r.height,nodes:Controller550W.getState().nodes};});assert(Math.abs(a.width/a.height-1920/1080)<.001);assert.equal(a.nodes,47);await p.close();return a;});
 await run('Mute removes all SFX and voice',async()=>{const s=baseSession('shutdown');s.audio.muted=true;s.audio.voiceEnabled=true;const p=await page('shutdown',s);await p.waitForFunction(()=>Controller550W.getState().finished);assert.equal((await state(p)).audioEvents.length,0);await p.close();});
 await run('Independent switches: voice can stay disabled with SFX on',async()=>{const p=await page('shutdown');await p.waitForFunction(()=>Controller550W.getState().finished);assert((await state(p)).audioEvents.length>0);assert.equal(p.errors.length,0);await p.close();});
 await run('Missing local audio and custom core fall back without FATAL',async()=>{const s=baseSession('shutdown');s.coreImagePath='absent.png';s.audio.audioFiles={SHUTDOWN_BEGIN:'absent.wav',POWER_OFF:'absent.mp3'};const p=await page('shutdown',s);await p.waitForFunction(()=>Controller550W.getState().finished);assert(!(await state(p)).events.some(x=>x.type==='FATAL'));await p.close();});
 await run('Repeated activation cannot repeat shutdown or relay sounds',async()=>{const s=baseSession('shutdown');s.preload=true;const p=await page('shutdown',s);await p.waitForFunction(()=>Controller550W.getState().events.some(x=>x.type==='PRELOAD_READY'));await send(p,{type:'activate'});await send(p,{type:'activate'});await p.waitForFunction(()=>Controller550W.getState().finished);const a=await state(p);assert.equal(a.events.filter(x=>x.type==='SHUTDOWN_BEGIN').length,1);assert.equal(a.audioEvents.filter(x=>x.key==='POWER_OFF').length,1);await p.close();});
 await run('Escape emergency skip',async()=>{const p=await page();await p.waitForTimeout(100);await p.keyboard.press('Escape');await p.waitForFunction(()=>Controller550W.getState().finished);assert((await state(p)).events.some(x=>x.type==='USER_SKIP'));await p.close();});
 await run('Click skip remains opt-in',async()=>{const p=await page();await p.mouse.click(100,100);assert.equal((await state(p)).finished,false);await p.keyboard.press('Escape');await p.close();const s=baseSession();s.settings.allowClickSkip=true;const q=await page('boot',s);await q.mouse.click(100,100);assert((await state(q)).finished);await q.close();});
 await run('Watchdog releases a stalled boot',async()=>{const s=baseSession();s.settings.bootWatchdogMs=700;const p=await page('boot',s);await p.waitForFunction(()=>Controller550W.getState().finished);assert((await state(p)).events.some(x=>x.type==='WATCHDOG'));await p.close();});
 await run('MinimumBootDuration remains an absolute floor at a faster theme speed',async()=>{const s=baseSession();s.minimumBootTimeMs=8000;s.settings.durationMultiplier=.25;const p=await page('boot',s);await send(p,{type:'target',target:{processDetected:true,windowDetected:true,ready:true}});await p.waitForFunction(()=>Controller550W.getState().finished);const a=await state(p);assert(a.events.find(e=>e.type==='TARGET_READY').at>=8000);assert(a.events.find(e=>e.type==='CHOREOGRAPHY_COMPLETE').at<8000);await p.close();return{events:a.events};});
 await run('Completed diagnostic sounds are one-shot per actual item',async()=>{const s=baseSession();s.settings.durationMultiplier=.1;const p=await page('boot',s);await p.waitForFunction(()=>Controller550W.getState().events.some(e=>e.type==='HUD_VISIBLE'));for(let i=0;i<4;i++){await send(p,{type:'diagnostics',row:{key:'cpu',value:'14%',status:'online'}});await send(p,{type:'diagnostics',row:{key:'external',value:'HTTPS READY',status:'online'}});}await p.waitForTimeout(300);const a=await state(p);assert.equal(a.audioEvents.filter(e=>e.identity==='diagnostic:cpu').length,1);assert.equal(a.audioEvents.filter(e=>e.identity==='diagnostic:external').length,1);await p.keyboard.press('Escape');await p.close();});
 await run('Voice-only mode substitutes app name and keeps its own volume',async()=>{const p=await browser.newPage();await p.goto(url+'/Themes/550W/boot.html?controlled');const a=await p.evaluate(async base=>{const {AudioKit}=await import('./js/audio.js');const said=[];Object.defineProperty(window,'speechSynthesis',{value:{speak:u=>{said.push({text:u.text,volume:u.volume});u.onend();},cancel:()=>{}}});base.audio.soundEnabled=false;base.audio.voiceEnabled=true;base.audio.voiceVolume=37;base.displayName='DeepSeek';const kit=new AudioKit(base,{audioEnabled:true,voiceEnabled:true,audioFiles:{TARGET_READY:'audio/ready.wav'}},()=>{});await kit.play('TARGET_READY');await kit.speak('READY');kit.dispose();return{said,sounds:kit.events};},baseSession());assert.equal(a.said.length,1);assert.equal(a.said[0].text,'DeepSeek interface ready');assert(Math.abs(a.said[0].volume-.37)<1e-6);assert.equal(a.sounds.length,0);await p.close();return a;});
 await run('Voice queue serializes requests and de-duplicates repeated events',async()=>{const p=await browser.newPage();await p.goto(url+'/Themes/550W/boot.html?controlled');const a=await p.evaluate(async base=>{const {AudioKit}=await import('./js/audio.js');window.chrome={webview:{}};base.audio.voiceEnabled=true;base.audio.phrases={BOOT:'550W 系统启动。',CORE:'核心模块初始化。',NETWORK:'网络连接已建立。'};const requests=[];let inflight=0,max=0;const kit=new AudioKit(base,{voiceEnabled:true,audioEnabled:true},m=>{requests.push(m.key);inflight++;max=Math.max(max,inflight);setTimeout(()=>{inflight--;kit.voiceDone(m.id);},45);});kit.speak('BOOT');kit.speak('CORE');kit.speak('CORE');await kit.speak('NETWORK');kit.dispose();return{requests,max};},baseSession());assert.deepEqual(a.requests,['BOOT','CORE','NETWORK']);assert.equal(a.max,1);await p.close();return a;});
 await run('Startup and shutdown voice flags work independently',async()=>{const p=await browser.newPage();await p.goto(url+'/Themes/550W/boot.html?controlled');const a=await p.evaluate(async base=>{const {AudioKit}=await import('./js/audio.js');const said=[];Object.defineProperty(window,'speechSynthesis',{value:{speak:u=>{said.push(u.text);u.onend();},cancel:()=>{}}});base.audio.voiceEnabled=true;base.audio.bootVoice=false;base.audio.shutdownVoice=true;const boot=new AudioKit(base,{voiceEnabled:true},()=>{});await boot.speak('READY');boot.dispose();base.kind='shutdown';const end=new AudioKit(base,{voiceEnabled:true},()=>{});await end.speak('SHUTDOWN');end.dispose();return said;},baseSession());assert.deepEqual(a,['正在终止人工智能会话。']);await p.close();});
 await run('Audio disposal stops queued machine voice requests',async()=>{const p=await browser.newPage();await p.goto(url+'/Themes/550W/boot.html?controlled');const a=await p.evaluate(async base=>{const {AudioKit}=await import('./js/audio.js');window.chrome={webview:{}};base.audio.voiceEnabled=true;base.audio.phrases={BOOT:'启动',CORE:'初始化'};const requests=[];const kit=new AudioKit(base,{voiceEnabled:true},m=>requests.push(m));kit.speak('BOOT');kit.speak('CORE');await new Promise(r=>setTimeout(r,25));kit.dispose();await kit.voiceQueue;return requests.map(m=>m.key);},baseSession());assert.deepEqual(a,['BOOT']);await p.close();});
 await run('Rendered offline machine voice uses the independent HTML Audio volume',async()=>{const p=await browser.newPage();await p.goto(url+'/Themes/550W/boot.html?controlled');const a=await p.evaluate(async base=>{const {AudioKit}=await import('./js/audio.js');window.chrome={webview:{}};base.audio.voiceEnabled=true;base.audio.soundEnabled=false;base.audio.voiceVolume=42;const played=[];window.Audio=class{constructor(url){this.url=url;}async play(){played.push({url:this.url,volume:this.volume});setTimeout(()=>this.onended(),25);}pause(){}};let kit;kit=new AudioKit(base,{voiceEnabled:true},m=>kit.voiceDone(m.id,'https://audio.550w.local/tts/generated.wav'));await kit.speak('READY');kit.dispose();return{played,active:kit.active.size,sounds:kit.events.length};},baseSession());assert.equal(a.played[0].volume,.42);assert.equal(a.played[0].url,'https://audio.550w.local/tts/generated.wav');assert.equal(a.active,0);assert.equal(a.sounds,0);await p.close();return a;});
 await run('Final Ready voice completes before interface handoff',async()=>{const p=await browser.newPage();await p.goto(url+'/Themes/550W/boot.html?controlled');await p.evaluate(()=>{window.voiceEnded=false;Object.defineProperty(window,'speechSynthesis',{value:{speak:u=>setTimeout(()=>{window.voiceEnded=true;u.onend();},1800),cancel:()=>{}}});});const s=baseSession();s.settings.durationMultiplier=.1;s.audio.voiceEnabled=true;s.audio.phrases={READY:'系统就绪。'};await send(p,{type:'init',session:s});await send(p,{type:'target',target:{processDetected:true,windowDetected:true,ready:true}});await p.waitForFunction(()=>Controller550W.getState().finished,{},{timeout:15000});const a=await state(p);assert(await p.evaluate(()=>window.voiceEnded));const ready=a.events.find(x=>x.type==='TARGET_READY').at,handoff=a.events.find(x=>x.type==='INTERFACE_HANDOFF').at;assert(handoff-ready>=1700);await p.close();return{ready,handoff};});
 const failures=results.filter(x=>!x.pass);console.log(JSON.stringify({passed:results.length-failures.length,total:results.length}));if(failures.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();server?.close();});
