// Focused V4.2 scan verification. No native window or real target application is opened.
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),images=path.join(root,'docs/images-v42');fs.mkdirSync(images,{recursive:true});
let browser,server,url;const only=process.argv.find(x=>x.startsWith("--only="))?.slice(7),resultPath=path.join(root,"docs/web-test-v42-results.json");const results=only&&fs.existsSync(resultPath)?JSON.parse(fs.readFileSync(resultPath)):[];
async function test(name,fn){if(only&&!name.startsWith(only))return;const old=results.findIndex(x=>x.name===name);if(old>=0)results.splice(old,1);try{results.push({name,pass:true,...await fn()});console.log('PASS '+name);}catch(e){results.push({name,pass:false,error:e.stack});console.error('FAIL '+name+' '+e.message);}fs.writeFileSync(path.join(root,'docs/web-test-v42-results.json'),JSON.stringify(results,null,2));}
async function scanState(p){return p.evaluate(()=>{const sh=document.querySelector('.controller-host').shadowRoot,eye=sh.querySelector('.boot-core img'),marks=sh.querySelector('.core-scanner');return{phase:fixture.intro.getState().phase,mask:eye.style.maskImage,opacity:getComputedStyle(eye).opacity,scannerOpacity:getComputedStyle(marks).opacity,background:getComputedStyle(fixture.stage).backgroundColor,points:[...marks.querySelectorAll('i')].map(n=>({x:parseFloat(n.style.left),y:parseFloat(n.style.top),color:getComputedStyle(n).backgroundColor,opacity:Number(n.style.opacity)})),beams:[...marks.querySelectorAll('b')].map(n=>{const m=new DOMMatrix(getComputedStyle(n).transform),w=parseFloat(n.style.width),x=parseFloat(n.style.left)*19.2,y=parseFloat(n.style.top)*10.8;return{x,y,ex:x+m.a*w,ey:y+m.b*w};}),lines:[...marks.querySelectorAll('.core-scan-line')].map(n=>({x:parseFloat(n.style.left),y:parseFloat(n.style.top),width:parseFloat(n.style.width),halves:[...n.children].map(h=>new DOMMatrix(getComputedStyle(h).transform).a)})),canvas:sh.querySelectorAll('.intro-particles').length};});}
const near=(a,b,message)=>assert(Math.abs(a-b)<.05,message+': '+a+' / '+b);
(async()=>{
 server=http.createServer((req,res)=>{if(req.url==='/fixture'){res.setHeader('Content-Type','text/html');res.end('<html><head></head><body></body></html>');return;}const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':file.endsWith('.json')?'application/json':file.endsWith('.png')?'image/png':file.endsWith('.wav')?'audio/wav':'application/octet-stream');fs.createReadStream(file).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));url='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({headless:true,executablePath:process.env.EDGE_PATH||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',args:['--autoplay-policy=no-user-gesture-required']});
 await test('four points / separate beam endpoints / joining bars / pixel-verified dual reveal',async()=>{
  const p=await browser.newPage({viewport:{width:1920,height:1080}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url+'/fixture');
  await p.evaluate(async()=>{
   const {createIntro}=await import('/Themes/550W/js/intro.js');document.documentElement.style.background='#000';document.body.style.cssText='margin:0;background:#000;overflow:hidden';
   const host=document.createElement('div');host.className='controller-host';host.style.cssText='position:absolute;left:50%;top:50%;width:1920px;height:1080px;transform:translate(-50%,-50%);';document.body.append(host);const sh=host.attachShadow({mode:'open'}),css=document.createElement('link');css.rel='stylesheet';css.href='/Themes/550W/css/controller.css';sh.append(css);await new Promise(r=>css.onload=r);
   const stage=document.createElement('div');stage.className='dsh550c-stage intro-active';stage.innerHTML='<div id="app"></div><div class="mechanical-core boot-core"><img src="/Themes/550W/assets/core.png"></div>';sh.append(stage);const core=stage.querySelector('.boot-core'),eye=core.querySelector('img');await eye.decode();const events=[];
   const intro=createIntro({stage,core,eye,settings:{coreHoldMs:2000,coreDissolveMs:200,particleResidueMs:200,logoRevealMs:200,logoHoldMs:200,logoBurstMs:200,multiWindowRevealMs:200},scale:x=>x,event:e=>events.push(e),finished:()=>false});await intro.prepare();
   let now=0,next;performance.now=()=>now;window.requestAnimationFrame=fn=>(next=fn,1);window.cancelAnimationFrame=()=>{next=null;};window.fixture={stage,eye,intro,events,step:t=>{now=t;const fn=next;next=null;fn(t);}};intro.play();await Promise.resolve();
  });
  const frames=[];async function step(t){await p.evaluate(t=>fixture.step(t),t);const s=await scanState(p);frames.push({at:t,...s});return s;}
  await step(0);let s=await step(78);assert.equal(s.opacity,'0');assert.deepEqual(s.points.map(x=>[x.x,x.y]),[[24,13],[76,13],[24,87],[76,87]]);assert(s.points.every(x=>x.color==='rgb(255, 59, 59)'));assert.equal(s.background,'rgb(0, 0, 0)');
  await p.screenshot({path:path.join(images,'01-four-red-points.png')});
  let previous=0;for(const t of [140,240,340,450]){s=await step(t);const beam=s.beams[0],distance=Math.hypot(beam.ex-beam.x,beam.ey-beam.y);assert(distance>previous);previous=distance;assert(s.beams.slice(0,2).every(b=>b.ey<540));assert(s.beams.slice(2).every(b=>b.ey>540));assert(s.beams[0].ex<s.beams[1].ex);assert.equal(s.opacity,'0');}
  await p.screenshot({path:path.join(images,'02-lasers-approaching.png')});
  s=await step(550);assert(s.lines.every(x=>x.halves.every(v=>v>0&&v<1)));await p.screenshot({path:path.join(images,'03-horizontal-lines-joining.png')});
  s=await step(640);for(let i=0;i<4;i++){near(s.beams[i].ex,i%2?1135:785,'separate beam endpoint x');near(s.beams[i].ey,i<2?365:715,'beam endpoint y');}assert(s.lines.every(x=>x.halves.every(v=>v===1)));assert.equal(s.lines[1].y-s.lines[0].y,350);
  let lastTop=365;for(const t of [720,855,1060,1285,1490]){s=await step(t);const [top,bottom]=s.lines;assert(top.y>lastTop);lastTop=top.y;near(top.y+bottom.y,1080,'scan symmetry');const edge=Math.max(0,Math.min(50,(top.y-375)/330*100));const values=[...s.mask.matchAll(/([\d.]+)%/g)].map(x=>Number(x[1]));assert.equal(values.length,6,s.mask);near(values[1],edge,'top mask matches line');near(values[2],edge,'top sharp mask');near(values[3],100-edge,'bottom mask matches line');near(values[4],100-edge,'bottom sharp mask');for(let i=0;i<4;i++)near(s.beams[i].ey,i<2?top.y:bottom.y,'diagonal remains connected');assert.equal(s.canvas,1);
   if(t===855){const png=await p.screenshot({path:path.join(images,'04-dual-scan-quarter.png')});const pixels=await p.evaluate(async data=>{const im=new Image();im.src='data:image/png;base64,'+data;await im.decode();const c=document.createElement('canvas');c.width=1920;c.height=1080;const cx=c.getContext('2d');cx.drawImage(im,0,0);function count(x,y,w,h){const a=cx.getImageData(x,y,w,h).data;let lit=0,nonblack=0;for(let i=0;i<a.length;i+=4){if(Math.max(a[i],a[i+1],a[i+2])>40)lit++;if(a[i]||a[i+1]||a[i+2])nonblack++;}return{lit,nonblack};}return{top:count(850,380,220,25),bottom:count(850,675,220,25),middle:count(850,475,220,130),background:count(30,450,200,200)};},png.toString('base64'));assert(pixels.top.lit>100&&pixels.bottom.lit>100,JSON.stringify(pixels));assert.equal(pixels.middle.nonblack,0,'unscanned middle is truly black');assert.equal(pixels.background.nonblack,0);}
   if(t===1060)await p.screenshot({path:path.join(images,'05-dual-scan-middle.png')});
  }
  s=await step(1500);assert.equal(s.scannerOpacity,'0');assert.equal(s.mask,'none');assert.equal(s.phase,'CORE_ILLUMINATED');
  await step(1920);await p.screenshot({path:path.join(images,'06-scan-complete.png')});
  // The fitted stage retains symmetric inset points on 16:10; no physical-corner clipping.
  await p.setViewportSize({width:1600,height:1000});await p.evaluate(()=>document.querySelector('.controller-host').style.transform='translate(-50%,-50%) scale('+Math.min(innerWidth/1920,innerHeight/1080)+')');const rects=await p.evaluate(()=>[...document.querySelector('.controller-host').shadowRoot.querySelectorAll('.core-scanner i')].map(n=>{const r=n.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2};}));assert(rects.every(r=>r.x>0&&r.x<1600&&r.y>0&&r.y<1000));near(rects[0].x+rects[1].x,1600,'16:10 point symmetry');near(rects[0].y+rects[2].y,1000,'16:10 vertical symmetry');
  for(const t of [2000,2200,2400,2600,2800,3000,3200])await step(t);const tail=await p.evaluate(()=>fixture.events);assert.deepEqual(tail.slice(-7),['CORE_PARTICLES','PARTICLE_RESIDUE','LOGO_ASSEMBLING','LOGO_BEGIN','LOGO_HOLD','LOGO_BURST','MULTIWINDOW_REVEAL','MULTIWINDOW_ACTIVE'].slice(-7));assert.equal(errors.length,0);await p.close();return{keyframes:frames,unscannedMiddle:'pixel checked: pure black',viewports:['1920x1080','1600x1000'],errors};
 });
 for(const [name,coreMs,multiplier]of [['short',500,1],['long',1600,1.5]])await test(name+' configured duration / existing particle-to-550C-to-HUD chain',async()=>{
  const p=await browser.newPage({viewport:{width:1920,height:1080}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url+'/Themes/550W/boot.html?controlled');await p.waitForFunction(()=>window.Controller550W);
  await p.evaluate(({coreMs,multiplier})=>{Controller550W.receive({type:'init',session:{kind:'boot',displayName:'Fixture AI',demo:true,minimumBootTimeMs:0,settings:{durationMultiplier:multiplier,colorProfile:'movie_red',systemLabel:'550W',coreHoldMs:coreMs,coreDissolveMs:180,particleResidueMs:180,logoRevealMs:180,logoHoldMs:180,logoBurstMs:180,multiWindowRevealMs:180,centerRevealMs:900,readyMs:600,shutdownMs:2600,fadeMs:300,bootWatchdogMs:30000,shutdownWatchdogMs:5000,waitForReady:true,allowEscape:true},audio:{soundEnabled:false,voiceEnabled:false,muted:true}}});Controller550W.receive({type:'target',target:{processDetected:true,windowDetected:true,ready:true}});},{coreMs,multiplier});
  await p.waitForFunction(()=>Controller550W.getState().intro?.phase==='MULTIWINDOW_ACTIVE',null,{timeout:15000,polling:5});const s=await p.evaluate(()=>Controller550W.getState()),times=Object.fromEntries(s.events.map(e=>[e.type,e.at])),actual=times.CORE_PARTICLES-times.CORE_SCANNING;assert(Math.abs(actual-coreMs*multiplier)<85,actual+' vs '+coreMs*multiplier);assert.equal(s.intro.count,700);assert.equal(s.nodes,47);
  const sequence=s.events.filter(e=>['CORE_PARTICLES','PARTICLE_RESIDUE','LOGO_ASSEMBLING','LOGO_HOLD','LOGO_BURST','MULTIWINDOW_REVEAL','MULTIWINDOW_ACTIVE'].includes(e.type)).map(e=>e.type);assert.equal(sequence.length,7);
  if(name==='short'){await p.waitForFunction(()=>Controller550W.getState().finished,null,{timeout:18000});const end=await p.evaluate(()=>Controller550W.getState());assert.equal(end.modules.length,9);assert(!end.events.some(e=>['FATAL','WATCHDOG'].includes(e.type)));}else await p.keyboard.press('Escape');assert.equal(errors.length,0);await p.close();return{coreExpectedMs:coreMs*multiplier,coreActualMs:actual,measurement:"CORE_SCANNING to CORE_PARTICLES (the clock starts on the first drawable RAF)",firstFrameDelayMs:times.CORE_SCANNING-times.CORE_INITIALIZING,particleCount:s.intro.count,hudNodes:s.nodes,sequence,errors};
 });
 if(results.some(x=>!x.pass))process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();server?.close();});
